In [1]:
! pip install torch

In [2]:
import torch

In [3]:
# 1, 2, 3이 들어있는 텐서를 생성
t1 = torch.tensor([1, 2, 3], dtype=torch.float32) #실수
# 2차원 텐서
t2 = torch.tensor([[4, 5], [6,7]])

t3 = torch.tensor([1.2,2.3,3.4])

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([[4, 5],
        [6, 7]])
tensor([1.2000, 2.3000, 3.4000])


In [4]:
tf=torch.FloatTensor([1,2,3]) # 실수형 텐서
f1=torch.LongTensor([1,2,3]) # 정수형 텐서
tb=torch.ByteTensor([1,2,3]) # 바이트형 텐서
print(tf)
print(f1)
print(tb)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3], dtype=torch.uint8)


In [5]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [6]:
x = torch.from_numpy(a) # NumPy 배열을 PyTorch 텐서로 변환
print(x)
print(type(x))

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
<class 'torch.Tensor'>


In [7]:
b= x.numpy()
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [8]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)
print(type(x), x.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'> torch.int64


In [9]:
y = x.float()
print(y)
print(y.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32


In [10]:
z = y.long()
print(z)
print(z.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64


In [11]:
z1 = y.byte()
print(z1)
print(z1.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.uint8)
torch.uint8


In [12]:
a = np.arange(1,13).reshape(3,2,2)
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [13]:
x = torch.from_numpy(a)
print(x.shape)
print(x.size())
print(x.dim())
print(x.ndim)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
3
3


In [14]:
#torch.Size([3, 2, 2])
print(x.size(0))  # 첫 번째 차원의 크기
print(x.size(1))  # 두 번째 차원의 크기
print(x.size(2))  # 세 번째 차원의 크기
print(x.size(-1))  # 마지막 차원의 크기

3
2
2
2


In [15]:
print(x.shape[0])
print(x.shape[1])
print(x.shape[2])
print(x.shape[-1])

3
2
2
2


In [16]:
#기본 연산
x = torch.tensor([[10, 12], [13, 14]])
y = torch.tensor([[5, 6], [7, 8]])
print('덧셈:', x + y)  # 덧셈
print('뺄셈:', x - y)  # 뺄셈
print('곱셈:', x * y)  # 곱셈
print('정수 나눗셈:', x // y) # 정수 나눗셈
print('나눗셈:', x / y)  # 나눗셈
print('나머지:', x % y)  # 나머지


덧셈: tensor([[15, 18],
        [20, 22]])
뺄셈: tensor([[5, 6],
        [6, 6]])
곱셈: tensor([[ 50,  72],
        [ 91, 112]])
정수 나눗셈: tensor([[2, 2],
        [1, 1]])
나눗셈: tensor([[2.0000, 2.0000],
        [1.8571, 1.7500]])
나머지: tensor([[0, 0],
        [6, 6]])


In [17]:
print(x**2) # 제곱
print(x**3) # 세제곱

tensor([[100, 144],
        [169, 196]])
tensor([[1000, 1728],
        [2197, 2744]])


In [18]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[2,2],[3,3]])
print(a==b) # 비교 연산
print(a!=b) # 비교 연산
print(a < b)  # a가 b보다 작은지
print(a > b)  # a가 b보다 큰지
print(a <= b)  # a가 b보다 작거나 같은지
print(a >= b)  # a가 b보다 크거나 같은지

print(torch.matmul(a, b))  # 행렬 곱셈
print(a @ b)  # 행렬 곱셈 (파이썬 3.5 이상에서 지원)

tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])
tensor([[ True, False],
        [False, False]])
tensor([[False, False],
        [False,  True]])
tensor([[ True,  True],
        [ True, False]])
tensor([[False,  True],
        [ True,  True]])
tensor([[ 8,  8],
        [18, 18]])
tensor([[ 8,  8],
        [18, 18]])


In [19]:
print(a.mul_(b))  # 행렬 곱셈
print(a)

tensor([[ 2,  4],
        [ 9, 12]])
tensor([[ 2,  4],
        [ 9, 12]])


In [20]:
a = np.arange(1, 13).reshape(3, 4)
print(a)

x = torch.from_numpy(a)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)


In [21]:
print(x.sum())  # 전체 원소의 합
print(x.sum(dim=0))  # 각 열의 합
print(x.sum(dim=1))  # 각 행의 합
print(x.sum(dim=-1))  # 마지막 차원의 합

tensor(78)
tensor([15, 18, 21, 24])
tensor([10, 26, 42])
tensor([10, 26, 42])


In [22]:
y = torch.tensor([1,2,3,4])
z = torch.tensor([5,6,7])
print(y)
print(x)
print(z)

tensor([1, 2, 3, 4])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([5, 6, 7])


In [23]:
print(x+10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]], dtype=torch.int32)


In [24]:
print(x+y)

tensor([[ 2,  4,  6,  8],
        [ 6,  8, 10, 12],
        [10, 12, 14, 16]])


In [25]:
#print(x+z) 차원이 맞지 않아서 오류 발생

In [26]:
a = np.arange(1, 13).reshape(3, 2, 2)
print(a)
x = torch.from_numpy(a)
y = torch.tensor([[1, 2], [3, 4]])
z = torch.tensor([1,2])
print(x)
print(y)
print(z)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]])
tensor([1, 2])


In [27]:
print(x+5) 

tensor([[[ 6,  7],
         [ 8,  9]],

        [[10, 11],
         [12, 13]],

        [[14, 15],
         [16, 17]]], dtype=torch.int32)


In [28]:
print(x+z) # y와 z의 크기가 다르므로 브로드캐스팅이 적용됨

tensor([[[ 2,  4],
         [ 4,  6]],

        [[ 6,  8],
         [ 8, 10]],

        [[10, 12],
         [12, 14]]])


In [29]:
print(x)
print(x.view(3, 4))  # 3행 4열로 모양 변경
print(x.view(2, 6))  # 2행 6열로 모양 변경
print(x.view(3, -1))  # 3행으로 변환, 열은 자동 계산
print(x.view(-1,4)) # 4열로 변환, 행은 자동 계산
print(x.reshape(4, 3)) # reshape는 view와 유사하지만, 메모리 복사를 허용함
print(x.reshape(3,4)) # 3행 4열로 모양 변경
print(x.reshape(2,6)) # 2행 6열로 모양 변경
print(x.reshape(3, -1)) # 3행으로 변환, 열은 자동 계산
print(x.reshape(-1, 4)) # 4열로 변환, 행은 자동 계산
print(x.reshape(-1)) # 1차원으로 변환
print(x.view(-1)) # 1차원으로 변환, view는 메모리 복사를 하지 않음


tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=to

In [30]:
y = x.view(3, 1, 4) # 3행 1열 4차원으로 모양 변경
print(y)
print(y.squeeze())  # 차원 축소
print(y.squeeze().shape)

tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
torch.Size([3, 4])


In [31]:
z

tensor([1, 2])

In [32]:
z1 = z.unsqueeze(1) 
print(z1) 
z2 = z.unsqueeze(0)
print(z2)  
print(x.size())

tensor([[1],
        [2]])
tensor([[1, 2]])
torch.Size([3, 2, 2])


In [33]:
x

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)

In [34]:
print(x[0]) # 첫 번째 행렬
print(x[0,0]) # 첫 번째 행렬의 첫 번째 원소
print(x[0, 0, 0]) # 첫 번째 행렬의 첫 번째 원소의 첫 번째 값

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([1, 2], dtype=torch.int32)
tensor(1, dtype=torch.int32)


In [35]:
print(x[1,:,-1])

tensor([6, 8], dtype=torch.int32)


In [36]:
a = np.arange(1,41).reshape(10,4)
x = torch.from_numpy(a)
print(x) # 10행 4열의 실수형 텐서

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36],
        [37, 38, 39, 40]], dtype=torch.int32)


In [37]:
split_x = torch.split(x, 4, dim=0)  # 첫 번째 차원(행)을 기준으로 2개씩 나눔
# print(split_x)  # 나눠진 텐서들 출력
for  sx in split_x:
    print(sx)  # 각 나눠진 텐서의 크기 출력
    print(sx.shape)  # 각 나눠진 텐서의 형태 출력

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]], dtype=torch.int32)
torch.Size([4, 4])
tensor([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]], dtype=torch.int32)
torch.Size([4, 4])
tensor([[33, 34, 35, 36],
        [37, 38, 39, 40]], dtype=torch.int32)
torch.Size([2, 4])


In [38]:
chunks = x.chunk(5, dim=0)  # 첫 번째 차원(행)을 기준으로 4개로 나눔
for chunk in chunks:
    print(chunk)  # 각 나눠진 텐서의 크기 출력
    print(chunk.shape)  # 각 나눠진 텐서의 형태 출력

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=torch.int32)
torch.Size([2, 4])
tensor([[ 9, 10, 11, 12],
        [13, 14, 15, 16]], dtype=torch.int32)
torch.Size([2, 4])
tensor([[17, 18, 19, 20],
        [21, 22, 23, 24]], dtype=torch.int32)
torch.Size([2, 4])
tensor([[25, 26, 27, 28],
        [29, 30, 31, 32]], dtype=torch.int32)
torch.Size([2, 4])
tensor([[33, 34, 35, 36],
        [37, 38, 39, 40]], dtype=torch.int32)
torch.Size([2, 4])


In [39]:
a = np.arange(1,13).reshape(3,2,2)
x = torch.from_numpy(a)  # NumPy 배열을 PyTorch 텐서로 변환
print(x)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)


In [40]:
indices = torch.LongTensor([2,1,0]) # 인덱스 텐서 생성
print(indices)
y = x.index_select(0, indices)  # 첫 번째 차원(행)을 기준으로 인덱스 선택
print(y)  # 선택된 행 출력

tensor([2, 1, 0])
tensor([[[ 9, 10],
         [11, 12]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 1,  2],
         [ 3,  4]]], dtype=torch.int32)


In [41]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(11,23).reshape(3,4)
x = torch.from_numpy(a)  # NumPy 배열을 PyTorch 텐서로 변환
y = torch.from_numpy(b)  # NumPy 배열을 PyTorch 텐서로 변환
print(x)
print(y)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]], dtype=torch.int32)


In [42]:
z = torch.cat((x, y), dim=0)    # 행 방향으로 x, y를 연결
print(z)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]], dtype=torch.int32)


In [43]:
z1 = torch.cat((x, y), dim=1)    # 열 방향으로 x, y를 연결
print(z1)

tensor([[ 1,  2,  3,  4, 11, 12, 13, 14],
        [ 5,  6,  7,  8, 15, 16, 17, 18],
        [ 9, 10, 11, 12, 19, 20, 21, 22]], dtype=torch.int32)


In [44]:
z2 = torch.stack((x, y), dim=0) # 행 방향으로 x, y를 다른 차원으로 묶은 텐서를 생성
print(z2)
print(z2.size())

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[11, 12, 13, 14],
         [15, 16, 17, 18],
         [19, 20, 21, 22]]], dtype=torch.int32)
torch.Size([2, 3, 4])


In [45]:
z3 = torch.stack((x, y), dim=1) # 열 방향으로 x, y를 다른 차원으로 묶은 텐서를 생성
print(z3)
print(z3.size())

tensor([[[ 1,  2,  3,  4],
         [11, 12, 13, 14]],

        [[ 5,  6,  7,  8],
         [15, 16, 17, 18]],

        [[ 9, 10, 11, 12],
         [19, 20, 21, 22]]], dtype=torch.int32)
torch.Size([3, 2, 4])


In [46]:
x = torch.FloatTensor([[[1, 2]], [[3, 4]]])
print(x.size())
print(x)

torch.Size([2, 1, 2])
tensor([[[1., 2.]],

        [[3., 4.]]])


In [47]:
y = x.expand(2, 2, 2)   # x의 크기를 (2, 2, 2)로 확장
print(y.size())
print(y)

torch.Size([2, 2, 2])
tensor([[[1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.]]])


In [48]:
x = torch.randperm(20)  # random permutation (0 ~ n-1 범위의 숫자를 n개 랜덤 수열 생성)
print(x)

tensor([ 1,  7,  5, 15, 12, 13, 10, 18,  3, 19,  9, 14,  4,  2, 11,  6,  8, 17,
        16,  0])


In [51]:
y = torch.randperm(3**3)
yr = y.reshape(3, 3, -1)    # 마지막 차원에 -1을 입력하면 알아서 크기를 맞춤
print(y)
print(yr)

tensor([13,  4, 18, 26, 25,  3, 17,  9, 24, 12, 14, 16,  7,  6, 10,  2, 11, 21,
        15, 22, 23,  0, 19,  5,  8, 20,  1])
tensor([[[13,  4, 18],
         [26, 25,  3],
         [17,  9, 24]],

        [[12, 14, 16],
         [ 7,  6, 10],
         [ 2, 11, 21]],

        [[15, 22, 23],
         [ 0, 19,  5],
         [ 8, 20,  1]]])


In [ ]:
y1 = yr.argmax(dim=0)   # x000, x100, x200에서 최고값의 인덱스를 찾음
print(y1)

tensor([[2, 2, 2],
        [0, 0, 1],
        [0, 2, 0]])


In [53]:
y2 = yr.argmax(dim=1)   # x01, x11, x21에서 최고값의 인덱스를 찾음
print(y2)

tensor([[1, 1, 2],
        [0, 0, 2],
        [0, 0, 0]])


In [ ]:
y3 = yr.argmax(dim=-1)   # 같은 행에서 최고값의 인덱스를 찾음 (-1은 마지막 차원이라는 의미. 3차원에선 2를 써도 같은 값이 나옴)
print(y3)

tensor([[2, 0, 2],
        [2, 2, 2],
        [2, 1, 1]])


In [ ]:
value, indices = torch.topk(y, k=1, dim=-1) # y의 dim=-1에서(같은 행에서) 최댓값 k개와 그 인덱스
print(value)
print(indices)

tensor([26])
tensor([3])


In [58]:
x = torch.FloatTensor([i for i in range(1, 10)]).view(3, 3)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [59]:
mask = x > 5
print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [60]:
y = x.masked_fill(mask, value=0)    # 마스크의 true부분을 0으로 반환
print(y)

tensor([[1., 2., 3.],
        [4., 5., 0.],
        [0., 0., 0.]])


In [ ]:
print(torch.ones(2,3)) 
print(torch.zeros(2,3))

print()

x=torch.FloatTensor([[1,2,3],[4,5,6], [7, 8, 9]]) 
print(x) 
print(x.size())
print()
print(torch.ones_like(x))   # x의 size인 (3, 3)으로 텐서를 만들겠다는 뜻
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([3, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
